### ISSUE TITLE
The role of run_http in user code

### ISSUE THREAD

**Issue by softprops** [davidbarsky/proto-lambda#1]
I'm not seeing the use case for run_http for user code. It seems to just wrap any event in a http request regardless of the trigger. non http triggers appear as http triggers that happen to transport event data in the request triggers body which is a little weird. In the case of an actual http trigger you'd have an http request object with an http request object inside its request wrappers body which is also weird.

What am I missing?

**Comment by davidbarsky** [comment]
Ah, yeah. I should expand the documentation there. Long story short—`run_http` _does not work right now_, but I was hoping to use to use the `run_http` as a specialized handler for ALB/API Gateway-invoked Lambdas that wouldn't _require_ exposing the proxied HTTP types that exist in [lambda-http](https://github.com/awslabs/aws-lambda-rust-runtime/tree/master/lambda-http)—you'd be able to use the http types _natively_, much like how [Zeit's `@now/rust`](https://zeit.co/docs/v2/deployments/official-builders/now-rust) works. In the future, I think this mechanism would make it easier to provide integration with web frameworks like Tide, Tower-Web, or Rocket.

The reason `run_http` needs to exist is that the `http` types don't implement Serde's `Serialize`/`Deserialize` traits (as I'm sure you're aware 😄).

Thing laterally, perhaps the `Serialize`/`Deserialize` bounds in `run` and `run_http` could be replaced with `Try{From, Into}`, if Serde introduces a blanket `Try{From, Into}` bound for `Serialize`/`Deserialize` _and_ if `http` replaces their homegrown implementation `HttpTry{From, Into}` with `TryFrom`/`TryInto`?

**Comment by softprops** [comment]
Gotcha. Is this the new repo to contribute to or will this be ported over to the aws labs account repo?

**Comment by davidbarsky** [comment]
It’ll be ported over to awslabs, and then aws.


________________________________
